# Generated by Django 4.0rc1 on 2023-04-26 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
